# site settings
title: SHINE Lab
subtitle: Institute of Cognitive Science
email: youremailaddress@gmail.com
description: System-Human Interaction with NIRS and EEG.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Institute of Cognitive Science, CU Boulder
city: Boulder
state: CO
zip_code: 80302
country: United States of America
phone: (720) 453-7902

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
