# site settings
title: SHINE Lab
subtitle: Institute of Cognitive Science
email: leanne.hirsfhield@colorado.edu
description: System-Human Interaction with NIRS and EEG.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://shinelaboratory.com # the base hostname & protocol for your site
author:
street_address: Institute of Cognitive Science, CU Boulder
city: Boulder
state: CO
zip_code: 80302
country: United States of America
phone: (720) 453-7902

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
